### PR TITLE
Cleanup strings

### PR DESCRIPTION
**Pull request by glynos**
I removed a lot of crap, mostly related to compile time switches on string types (we never use std::wstring, so I made everything a std::string). I was able to remove some files and traits classes that are not needed.

### CODE REVIEW

**Comment by deanberris** [comment]
The build is borked, mind having a look?

**Comment by glynos** [comment]
It only gets as far as a call to cURL at the beginning of the build...

```
The command "curl -sSL "http://llvm.org/apt/llvm-snapshot.gpg.key" | sudo -E apt-key add -" failed and exited with 2 during .
```

I don't know what this means.

**Comment by deanberris** [comment]
Interesting. This means that the LLVM apt repository (PPA) isn't available at the time the tests ran. I'll retry it and see if this error is transient.

**Comment by glynos** [comment]
http://stackoverflow.com/questions/37558151/travis-ci-build-failing

**Comment by glynos** [comment]
Still no luck with the availability of the LLVM apt repo. Will you be able to test it locally? I would be OK to merge these changes without Travis for now if it works for you, so we are not blocked.

**Pull request closed without merging**
