### PR TITLE
Use c++11 flag for gcc, clang fixes #232

### LINKED ISSUE #232: Client destructor hangs in 64-bit C++11 mode
When I compile the following program asa 64-bit program in C++11 mode, and run it:

``` c++
#include <boost/network/protocol/http/client.hpp>

int main(int argc, char** argv)
{
    using namespace boost::network;
    using namespace boost::network::http;

    std::string result = body(client().get(client::request("http://www.boost.org/")));
}
```

the program hangs. The stack trace is the following:

```
#0  0x00007ffff72d785c in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/libpthread.so.0
#1  0x000000000045d973 in boost::thread::join() ()
#2  0x000000000042be15 in boost::network::http::impl::async_client<boost::network::http::tags::http_async_8bit_udp_resolve, 1u, 1u>::~async_client (this=0x8002f0,
    __in_chrg=<optimized out>) at cpp-netlib/boost/network/protocol/http/client/async_impl.hpp:73
#3  0x000000000042fd6c in boost::network::http::basic_client_impl<boost::network::http::tags::http_async_8bit_udp_resolve, 1u, 1u>::~basic_client_impl (this=0x8002f0,
    __in_chrg=<optimized out>) at cpp-netlib/boost/network/protocol/http/client/pimpl.hpp:79
#4  0x000000000042e5fb in boost::checked_delete<boost::network::http::basic_client_impl<boost::network::http::tags::http_async_8bit_udp_resolve, 1u, 1u> > (x=0x8002f0)
    at boost/boost/checked_delete.hpp:34
#5  0x000000000043fa0c in boost::detail::sp_counted_impl_p<boost::network::http::basic_client_impl<boost::network::http::tags::http_async_8bit_udp_resolve, 1u, 1u> >::dispose (
    this=0x801150) at boost/boost/smart_ptr/detail/sp_counted_impl.hpp:78
#6  0x000000000040d974 in boost::detail::sp_counted_base::release (this=0x801150) at boost/boost/smart_ptr/detail/sp_counted_base_gcc_x86.hpp:145
#7  0x000000000040da37 in boost::detail::shared_count::~shared_count (this=0x7fffffffdc28, __in_chrg=<optimized out>)
    at boost/boost/smart_ptr/detail/shared_count.hpp:305
#8  0x0000000000415d70 in boost::shared_ptr<boost::network::http::basic_client_impl<boost::network::http::tags::http_async_8bit_udp_resolve, 1u, 1u> >::~shared_ptr (this=0x7fffffffdc20,
    __in_chrg=<optimized out>) at boost/boost/smart_ptr/shared_ptr.hpp:164
#9  0x0000000000415d8a in boost::network::http::basic_client_facade<boost::network::http::tags::http_async_8bit_udp_resolve, 1u, 1u>::~basic_client_facade (this=0x7fffffffdc20,
    __in_chrg=<optimized out>) at cpp-netlib/boost/network/protocol/http/client/facade.hpp:23
#10 0x0000000000415da4 in boost::network::http::basic_client<boost::network::http::tags::http_async_8bit_udp_resolve, 1u, 1u>::~basic_client (this=0x7fffffffdc20,
    __in_chrg=<optimized out>) at cpp-netlib/boost/network/protocol/http/client.hpp:33
#11 0x000000000040c78c in main (argc=1, argv=0x7fffffffdd28) at test.cpp:8
```

Interestingly, if I build the program in 32-bit mode, or without the C++11 flag, it works fine.

This happens regardless of whether boost and cpp-netlib are also built in C++11 mode.

Some more information:
  compiler: gcc 4.8
  OS: Ubuntu 10.04
  boost version: I tried with both 1.51 and trunk
  cpp-netlib version: 0.9.4

I have the strangest feeling that I've encountered this issue before, and solved it, but I cannot for the life of me remember how.

Any ideas?

### PR DESCRIPTION
**Pull request by niklas88**
This fixes a deadlock for me when building e.g. the twitter_search example
with -std=c++11, similar to https://github.com/cpp-netlib/cpp-netlib/issues/232
but even without temporary lifetime of the client.

### CODE REVIEW

**Comment by glynos** [comment]
It looks like none of the builds succeeded with these changes. What compiler did you test with locally? 

In fact, I think the problem is not with the changes you have made, but with the fact that we are apparently using legacy infrastructure on Travis. It looks like we have work to do to upgrade here.

**Comment by niklas88** [comment]
:D I'm using GCC 5.1

**Comment by deanberris** [comment]
I agree -- however, I'm not sure how to do this upgrade @glynos -- would you or @niklas88 know?

**Comment by deanberris** [comment]
So, we're already using C++11 in the master branch, so the next version of the library will require C++11 features.

**Pull request closed without merging**
