### PR TITLE
Link with standard libraries instead of Boost

### PR DESCRIPTION
**Pull request by glynos**
I added a submodule to the last official release of Asio, which uses standard library components instead of Boost.System, and updated all the internal code to reflect this.

I discovered some tests weren't running correctly (actually weren't ever running correctly), e.g. the MIME tests, and the client timeout tests, and I have disabled all of these.

I removed the filesystem path converter for the URI.

This is all backward incompatible now, and will break user code.

### CODE REVIEW

**Comment by glynos** [comment]
It seems the check that it is failing is for one of the configurations using the sanitizer. I ran this locally without any issues... any ideas?

**Comment by deanberris** [comment]
It looks like a clang version might not be able to handle C++14 features (if we're already using those), or potentially a bug with the thread sanitiser with the version of clang we're using. Can you try upgrading the version in the travis config to see if that would resolve it? It's unfortunate that we don't see where the segfault happens when running on Travis, that would give us a lot more information.

**Comment by glynos** [comment]
We build using the -std=c++11 flag, so it is unlikely that it is an issue with C++14 features. I have updated the Travis config to use clang 3.7 (which I am using) to see if that solves the issue.

**Comment by deanberris** [comment]
Okay, I think this is all good now. Thanks @glynos!

**Comment by deanberris** [comment]
LGTM

**Pull request merged**
