### PR TITLE
Boost future master

### PR DESCRIPTION
**Pull request by cinghiale**
This is #684 against the master branch

### CODE REVIEW

**Comment by glynos** [comment]
All tests on Travis failed.

@cinghiale ignore the tests for clang right now, we already now that they don't work. However, it looks like you have added a dependency to Boost.System to cpp-netlib, and their is a linking error for the tests and examples.

**Comment by cinghiale** [comment]
Added the missing libraries. Waiting for the CI...

**Comment by cinghiale** [comment]
Still some failures... I'll try to fix soon

**Comment by cinghiale** [comment]
@glynos  I'm a bit puzzled by the failings. Looking at the output it looks like we found an ICE in one of the tests:

```
[ 90%] Building CXX object libs/network/test/http/CMakeFiles/cpp-netlib-http-server_async_run_stop_concurrency.dir/server_async_run_stop_concurrency.cpp.o
[snip]
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
```

On my ubuntu box (16.10) I have access to gcc 4.8.5 and it compiles fine.

any suggestion is very appreciated

**Comment by deanberris** [comment]
I think we don't need to block this on the CI results. We should be able to fix this after the fact.

**Comment by deanberris** [comment]
LGTM

**Pull request merged**
