### PR TITLE
Update Travis configuration

### PR DESCRIPTION
**Pull request by deanberris**
This change includes the following:
- Leverage the caching feature by setting 'sudo' to false and caching
  the Boost directory.
- Test against later versions of Boost (up to 1.58.0).
- Use modular boost by default.
- Remove special-case handling of dynamic and static libraries.

### CODE REVIEW

**Comment by deanberris** [comment]
@glynos -- If you have time, please have a look. The Travis configuration upgrade is an attempt to use caching, which I think I don't understand whether or not it's working. The real advantage here is that we're using the containerised version of the worker, which if we get the caching to work properly gives us faster/quicker integration testing.

I was mostly following http://docs.travis-ci.com/user/caching/ -- I'm not sure I understand why things are failing to cache.

Whether we can upgrade the compilers from the containerised environment is something I'm not sure is possible. Probably worth exploring with Travis and the public offering.

**Comment by glynos** [comment]
I think I need to take a little time to understand the changes you made (and the new Travis system you're taking advantage of).

Why are you making all these changes on the 0.11 branch and not master?

**Comment by deanberris** [comment]
I'm trying to get the 0.11-devel branch to get tested in C++11 mode, because apparently most users are running into issues there. If these work, I'll port the changes into master. Does that make sense @glynos? Thanks in advance.

**Comment by glynos** [comment]
To keep 0.11-devel up-to-date it makes sense, just that all these changes will need to be duplicated to continue working on master.

**Comment by glynos** [comment]
Travis for lots of configuration with this:

    Still running (20 of 20): ./install-boost.sh
    Timeout (20 minutes) reached. Terminating "./install-boost.sh"
    The command "travis_wait ./install-boost.sh" failed and exited with 1 during .

Otherwise all clang builds are failing with this being reported multiple times:

    cc1plus: error: unrecognized command line option ‘-std=c++11’

**Comment by deanberris** [comment]
Yeah, I've been running into too many issues here. I'll leave this alone and see whether I can figure something out that works at some point in the future. Probably find a way to test against more recent Boost releases using PPA's.

Thanks @glynos.

**Comment by deanberris** [comment]
This one is defunct now, we're already using the containerised environment with caching. I'm closing this PR now.

**Pull request closed without merging**
