### PR TITLE
fix cpp-netlib-http-client_get_timeout_test - change broken link

### PR DESCRIPTION
**Pull request by cnagune**
* problem
```
$ make test
Running tests...
...
      Start 15: cpp-netlib-http-client_get_timeout_test
15/20 Test #15: cpp-netlib-http-client_get_timeout_test .............***Failed   13.78 sec
...
$ curl "http://cznic.dl.sourceforge.net/project/boost/boost/1.55.0/boost_1_55_0.tar.bz2"
<html>
<head><title>302 Found</title></head>
<body bgcolor="white">
<center><h1>302 Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

* fix
```
$ make test
Running tests...
...
      Start 15: cpp-netlib-http-client_get_timeout_test
15/20 Test #15: cpp-netlib-http-client_get_timeout_test .............   Passed   15.58 sec
...
```

### CODE REVIEW

**Comment by leecoder** [comment]
I've rewrote this tc using localhost server. (leecoder@e5fa067dff3cccc3dabbb264f8277289fa3bf8c0)

**Comment by deanberris** [comment]
It looks like it's still broken @cnagune -- @leecoder did you have a PR for this?

**Comment by leecoder** [comment]
I've created a new PR #533 .

**Comment by deanberris** [comment]
Thanks @leecoder -- @cnagune I think you can close this now that we have a more reliable fix in the meantime. Thank you both for your efforts and contributions!

**Pull request closed without merging**
