### PR TITLE
Doxygen+Sphinx+Breathe = Inline Documentation

### PR DESCRIPTION
**Pull request by deanberris**
This is the initial attempt at getting inline documentation in the
project implementation into the sphinx-generated documentation. The way
we achieve this is by doing the following:

  - Add michaeljones/breathe as a submodule, making it simpler to
    generate the documentation with just Sphinx installed on the
    developer machine.
  - Define a Doxyfile configuration which generates HTML and XML
    documentation. The generated XML files are needed by Breathe to
    generate the HTML as part of the Sphinx docs generation process.
  - Update the documentation for the client type. This is a starting
    point showing how the generated docs are in-lined in the RST docs
    via breathe.
  - Wire up the documentation generation in the Sphinx configuration.

To generate the documentation now, we need two things installed on the
machine generating the docs: Sphinx and Doxygen. The steps involved are:

  1. cd cpp-netlib && doxygen
  2. cd libs/network/doc/ && make html

The results should be in libs/network/doc/_build/html, and the
generated HTML for the HTTP Client reference page should include the
doxygen-generated docs.

### CODE REVIEW

**Comment by deanberris** [comment]
Hi @glynos -- are you able to have a look at this?

**Comment by deanberris** [comment]
Thanks @glynos!

**Comment by davidvandebunte** [comment]
@deanberris See the issue linked above.

FWIW, it looks like 853385ef4f0c3dd126887750e20d5f7456065998 (the commit you pointed this submodule at) is equivalent to a564b991b5eb2dc220ca29ef21b9c68bdc2f8ac6 in their new history. Perhaps this submodule should be updated to point to this new commit?

**Comment by deanberris** [comment]
Thanks @davidvandebunte -- merged your PR. :)

**Pull request merged**
