### PR TITLE
Generating bad object file by Xcode 6.1 fix

### PR DESCRIPTION
**Pull request by toolbits**
Generating bad object file by Xcode 6.1 fix.
Issue #466

### CODE REVIEW

**Comment by deanberris** [comment]
So having had a look at this, it seems it's broken according to Travis. Can you fix the breakages and then try again? Or, as I suspect, since I've merged another pull request that touches these things you may need to re-do this in another branch. See http://cpp-netlib.org/process.html for a hint on how I prefer to do bug-fix-branches.

**Comment by deanberris** [comment]
@toolbits -- do you have time to update this PR?

**Comment by toolbits** [comment]
Hi, I have little time in this week.
I'm trying to fix this error. Please wait...

**Comment by mikhailberis** [comment]
Thanks — looking forward to the update!

**Comment by deanberris** [comment]
Looks like this is still broken @toolbits -- you might want to look at the results from Travis (https://travis-ci.org/cpp-netlib/cpp-netlib/builds/57927023) so that you can perhaps debug better? Or you might want to rebase from the latest in 0.11-devel?

**Comment by ksl67** [comment]
I tried this against v0.11.2 and I can confirm that when I run my application (built in debug mode) in Xcode 6.3.2, it no longer crashes.

**Comment by deanberris** [comment]
This is superseded by #578.

**Pull request closed without merging**
