### PR TITLE
Added example to store large streaming data directly to filesystem

### PR DESCRIPTION
**Pull request by carun**
Added example to store large streaming data directly to filesystem using async server. I have tried to modify the CMakeLists.txt so that this example will be built only if a C++11 compiler is found. But I have not got a chance to test it on a compiler that doesn't support C++11.

Please let me know if this looks fine.

### CODE REVIEW

**Comment by deanberris** [comment]
@carun -- Any update on this?

**Comment by carun** [comment]
@deanberris -- Hi Deam, I'm so sorry.I have not used git before. So I was struggling to take it to the C+11 branch, messed my repo twice (I use hg all the time). Please let me know how to proceed further.  I don't have time to work on this right now. But if there is a way to take these changes to the right branch, I would appreciate your help.

**Comment by mikhailberis** [comment]
Have you tried following the steps outlined here: http://cpp-netlib.org/process.html#pull-requests <http://cpp-netlib.org/process.html#pull-requests> ?

**Comment by deanberris** [comment]
Closing for lack of response. If you still have time and still want to get this in, I'd love to review it again @carun.

**Pull request closed without merging**
