### PR TITLE
Enable remove_chunk_markers by default. Fix a bug and add a comment.

### PR DESCRIPTION
**Pull request by igorpeshansky**

### CODE REVIEW

**Comment by igorpeshansky** [comment]
@deanberris PTAL.
@umennel FYI.

**Comment by deanberris** [comment]
Thanks, @igorpeshansky -- would it make sense if you merge these into 0.13-release as well? It may not be a straight-forward merge.

**Comment by igorpeshansky** [comment]
@deanberris Did you mean both #720 and #830?

**Comment by deanberris** [comment]
@igorpeshansky Yes, both those would be good to see in 0.13-release.

**Comment by umennel** [comment]
Cherry-picked commits from both PRs with #833

**Pull request merged**
