### PR TITLE
Update boost to std

### PR DESCRIPTION
**Pull request by glynos**
@deanberris 

I took the leap ... as far as I possibly could I replaced boost classes/functions with their C++11/14 equivalents.

There's still a lot to do. I did not touch the code that depends on MPL/type traits because I think this should be eventually replaced (all the message stuff).

The thread pool still uses boost::thread_group, but I think it would be trivial to implement it ourselves (therefore we won't need to link to boost thread at all). As for the other boost static libraries, they are really only needed for some dependencies and for the examples.

Also, I did not touch the cpp-netlib MIME code (I don't know what to do with it, though I suspect it would continue to work if we used C++11/14 here).

Eventually I want to be able to build cpp-netlib without an external dependency to boost or asio. We can later use the boost-free asio, and for the rest a shrink-wrapped (header-only) boost.

Let's talk on slack if you want more info.

### CODE REVIEW

**Comment by deanberris** [comment]
Wow, and Travis is *green*! Thanks @glynos -- I'll have a look soon!

**Comment by deanberris** [comment]
I see you've removed the Twitter example -- did we need to update anything from the docs for that? Just wondering, I don't think we need to make the change now.

**Comment by deanberris** [comment]
LGTM -- skimmed it, and I'm happy that Travis is green.

Thanks again @glynos!

**Comment by glynos** [comment]
I didn't update any documentation. We should go through that anyway, because I think it is out-od-date in a lot of ways.

twiitter_search has been a bit of an embarrassment because it just crashed, that's why I removed it completely. We need better examples.

**Pull request merged**
