### PR TITLE
fix http client timeout

### PR DESCRIPTION
**Pull request by chenzhaoyu**
Hi, in our usage of cpp-netlib(version cpp-netlib-0.12.0-final), we meet this issue:
sometimes, http request is finished, but http client destruct will  be blocked until client timeout.
I think this code has a issue:
If http callback thread run before timer_.async_wait(), timer will not been cancel.

I try to fix it, WDYT?

### CODE REVIEW

**Comment by LoopinFool** [comment]
This change seems correct, and "looks good to me". If it gets merged, please consider also merging into other branches (0.12-release that chenzhaoyu is probably using, and 0.13-release that I am using). Thanks.

**Comment by anonimal** [comment]
@deanberris @glynos ?

**Comment by deanberris** [comment]
LGTM -- apologies for the delay here, been too busy with other things. :(

**Comment by maingoh** [comment]
Hello,

I have very rarely some connections timeout with images on google storage. I am not sure it is an issue on google side so I was wondering what this PR does and if it is possible to merge it to 0.13 branch ?

Thank you,

**Comment by deanberris** [comment]
@maingoh -- Can you test to see whether this, when applied to 0.13-release fixes the issue for you? If so I'd be happy to merge a PR that cherry-picks this into 0.13-release. An -rc1 should be forthcoming later in the week, and it'd be great to have this fix in the next release candidate.

**Comment by maingoh** [comment]
I will try to test it, not sure I can give a feedback this week though.. Also I read better what the PR does and I don't think it is related to my issue, I don't destruct the client.
My issue is : 
- I have many images to download from google storage (10k). 
- I have approximately 3 simultaneous requests.
- I get ~10 requests that timed out

I am not sure this is normal or not

**Pull request merged**
