### PR TITLE
fixed async client multithread problem

### PR DESCRIPTION
**Pull request by dptr**
async client crashes in multithread condition, because
the boost::spirit grammar object is not thread safe without /DBOOST_SPIRIT_THREADSAFE

the detailed discussion can be seen below:
https://groups.google.com/forum/#!topic/cpp-netlib/yqa5Qtpc1j4

### CODE REVIEW

**Comment by dptr** [comment]
Remove the static keyword may reduce performance.
I changed /D to -D in the CMakeLists.txt and tested with g++ compiler and MSVC. It worked fine.

**Comment by glynos** [comment]
Sorry, this failed really badly on Travis. Redefining CMAKE_CXX_FLAGS overwrites a lot of other things. To get what you're looking for, try add_definitions:

https://cmake.org/cmake/help/v3.1/command/add_definitions.html

**Comment by glynos** [comment]
Also, I'm surprised that you say it compiles with MSVC. Which version?

**Comment by dptr** [comment]
I compiled the cppnetlib-uri project with Visual Studio 2010.

**Comment by dptr** [comment]
Thanks for your advice aboult CMAKE_CXX_FLAGS. I delete my old fork so create another pull request.

**Pull request closed without merging**
